apiVersion: 1
groups:
    - orgId: 1
      name: Operator Eval Group
      folder: operator
      interval: 1m
      rules:
        - uid: aeecqkn99byf4c
          title: Operator Started
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: loki
              model:
                datasource:
                  type: loki
                  uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera_operator"} |= `Operator Node successfully spawned!` [1m]) > 0
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: Operator is started
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: aeecr7yv265mod
          title: Operator Restarting
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: loki
              model:
                datasource:
                    type: loki
                    uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera_operator"} |= `Restarting Drosera Operator node` [1m]) > 0
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: Operator is attempting to restart
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: abcd7yv265mod
          title: Operator Shutdown
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: loki
              model:
                datasource:
                    type: loki
                    uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera_operator"} |= `Shutting down Drosera Operator node` [1m]) > 0
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: Operator was shutdown
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: bdca7yv265mod
          title: Operator No Working RPCs
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: loki
              model:
                datasource:
                    type: loki
                    uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera_operator"} |= `All ETH RPC nodes are unresponsive. Shutting down operator node` [1m]) > 0
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: All ETH RPC nodes are unresponsive, operator is shutting down completely
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
    - orgId: 1
      name: Seed Node Eval Group
      folder: seed-node
      interval: 1m
      rules:
        - uid: mhraqkn99byf4c
          title: Seed Node Started
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: loki
              model:
                datasource:
                  type: loki
                  uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera_seed_node"} |= `Seed Node successfully spawned!` [1m]) > 0
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: Seed Node is started
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: pxyaqkn99byf4c
          title: Seed Node Shut Down
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: loki
              model:
                datasource:
                  type: loki
                  uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera_seed_node"} |= `Shutting down Drosera seed node` [1m]) > 0
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: Seed Node was shut down
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: olmwqkn99byf4c
          title: Seed Node Restarting
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: loki
              model:
                datasource:
                  type: loki
                  uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera_seed_node"} |= `Restarting Drosera seed node` [1m]) > 0
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: Seed Node is attempting to restart
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: xirsqkn99byf4c
          title: Seed Node No Working RPCs
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: loki
              model:
                datasource:
                  type: loki
                  uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera_seed_node"} |= `All ETH RPC nodes are unresponsive. Shutting down seed node` [1m]) > 0
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: All ETH RPC nodes are unresponsive, seed node is shutting down completely
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
    - orgId: 1
      name: Proof Server Eval Group
      folder: proof-server
      interval: 1m
      rules:
        - uid: jurxqkn99byf4c
          title: Proof Server Started
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: loki
              model:
                datasource:
                  type: loki
                  uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera-proof-server"} |= `Proof Server listening on` [1m]) > 0
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: Proof Server was started
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: ustzqkn99byf4c
          title: Proof Server Shut Down
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: loki
              model:
                datasource:
                  type: loki
                  uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera-proof-server"} |= `Server shutdown` [10m]) > 0
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: Proof Server was shut down
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: bef1le9mw2ewwf
          title: High CPU %
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: prometheus
              model:
                disableTextWrap: false
                editorMode: builder
                expr: avg_over_time(proof_server_process_cpu_usage_percent[1m]) > 75
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            description: The proof server CPU percentage has breached 25% for the past minute on average
            summary: High proof server CPU percentage
          labels: {}
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: o4hlle9mw2ewwf
          title: High Storage Usage
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: prometheus
              model:
                disableTextWrap: false
                editorMode: builder
                expr: proof_server_process_disk_space_usage_MB > 1000
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            description: The proof server is using more than 1 GB of storage
            summary: High proof server storage usage
          labels: {}
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
