apiVersion: 1
groups:
    - orgId: 1
      name: Operator Eval Group
      folder: operator
      interval: 1m
      rules:
        - uid: aeecqkn99byf4c
          title: Operator Started
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: loki
              model:
                datasource:
                  type: loki
                  uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera_operator"} |= `Operator Node successfully spawned!` [10m]) > 0
                intervalMs: 30000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: Operator is started
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: aeecr7yv265mod
          title: Operator Restarting
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: loki
              model:
                datasource:
                    type: loki
                    uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera_operator"} |= `Restarting Drosera Operator node` [10m]) > 0
                intervalMs: 30000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: Operator is attempting to restart
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: abcd7yv265mod
          title: Operator Shutdown
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: loki
              model:
                datasource:
                    type: loki
                    uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera_operator"} |= `Shutting down Drosera Operator node` [10m]) > 0
                intervalMs: 30000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: Operator was shutdown
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: bdca7yv265mod
          title: Operator No Working RPCs
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: loki
              model:
                datasource:
                    type: loki
                    uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera_operator"} |= `All ETH RPC nodes are unresponsive. Shutting down operator node` [10m]) > 0
                intervalMs: 30000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: All ETH RPC nodes are unresponsive, operator is shutting down completely
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: eeibub6g9pxq8b
          title: Operator Low ETH Balance
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: prometheus
              model:
                datasource:
                    type: prometheus
                    uid: prometheus
                disableTextWrap: false
                editorMode: builder
                exemplar: false
                expr: eth_balance_ETH{service_name="drosera_operator"}
                format: table
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                interval: ""
                intervalMs: 30000
                legendFormat: 'Operator: {{operator_address}}'
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: C
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.05
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 30000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: feibsm0m2uepse
          panelId: 7
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: feibsm0m2uepse
            __panelId__: "7"
            description: "The operator {{ $labels.operator_address }} has fallen below the minimum threshold for a safe ETH balance. Current balance: {{ $values.A.Value }} ETH"
            summary: "Low ETH Balance ({{ $values.A.Value }} ETH)"
          labels: {}
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: i7r1le9mw2epxk
          title: Operator High CPU %
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 300  # 5 minutes
                to: 0
              datasourceUid: prometheus
              model:
                disableTextWrap: false
                editorMode: builder
                expr: avg_over_time(drosera_process_cpu_usage_percent[5m]) > 75
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 30000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            description: "The operator CPU percentage has breached 75% for the past 5 minutes on average"
            summary: "High operator CPU percentage ({{ $values.A.Value }}%)"
            __dashboardUid__: feibsm0m2uepse
            __panelId__: "4"
          labels: {}
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
    - orgId: 1
      name: Seed Node Eval Group
      folder: seed-node
      interval: 10m
      rules:
        - uid: mhraqkn99byf4c
          title: Seed Node Started
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: loki
              model:
                datasource:
                  type: loki
                  uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera_seed_node"} |= `Seed Node successfully spawned!` [10m]) > 0
                intervalMs: 30000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: Seed Node is started
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: pxyaqkn99byf4c
          title: Seed Node Shut Down
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: loki
              model:
                datasource:
                  type: loki
                  uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera_seed_node"} |= `Shutting down Drosera seed node` [10m]) > 0
                intervalMs: 30000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: Seed Node was shut down
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: olmwqkn99byf4c
          title: Seed Node Restarting
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: loki
              model:
                datasource:
                  type: loki
                  uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera_seed_node"} |= `Restarting Drosera seed node` [10m]) > 0
                intervalMs: 30000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: Seed Node is attempting to restart
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: xirsqkn99byf4c
          title: Seed Node No Working RPCs
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: loki
              model:
                datasource:
                  type: loki
                  uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera_seed_node"} |= `All ETH RPC nodes are unresponsive. Shutting down seed node` [10m]) > 0
                intervalMs: 30000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: All ETH RPC nodes are unresponsive, seed node is shutting down completely
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: o9x4le9mw2hj7f
          title: Seed Node High CPU %
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 300  # 5 minutes
                to: 0
              datasourceUid: prometheus
              model:
                disableTextWrap: false
                editorMode: builder
                expr: avg_over_time(seed_node_process_cpu_usage_percent[5m]) > 75
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 30000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            description: "The seed node CPU percentage has breached 75% for the past 5 minutes on average"
            summary: "High seed node CPU percentage ({{ $values.A.Value }}%)"
            __dashboardUid__: bobasm0m2uepse
            __panelId__: "4"
          labels: {}
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
    - orgId: 1
      name: Proof Server Eval Group
      folder: proof-server
      interval: 10m
      rules:
        - uid: jurxqkn99byf4c
          title: Proof Server Started
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: loki
              model:
                datasource:
                  type: loki
                  uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera-proof-server"} |= `Proof Server listening on` [10m]) > 0
                intervalMs: 30000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: Proof Server was started
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: ustzqkn99byf4c
          title: Proof Server Shut Down
          condition: A
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: loki
              model:
                datasource:
                  type: loki
                  uid: loki
                editorMode: builder
                expr: count_over_time({service_name="drosera-proof-server"} |= `Server shutdown` [10m]) > 0
                intervalMs: 30000
                maxDataPoints: 43200
                queryType: instant
                refId: A
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: Proof Server was shut down
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: bef1le9mw2ewwf
          title: High CPU %
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 300  # 5 minutes
                to: 0
              datasourceUid: prometheus
              model:
                disableTextWrap: false
                editorMode: builder
                expr: avg_over_time(proof_server_process_cpu_usage_percent[5m]) > 75
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 30000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            description: "The proof server CPU percentage has breached 75% for the past 5 minutes on average"
            summary: "High proof server CPU percentage ({{ $values.A.Value }}%)"
            __dashboardUid__: aeies2bb7iy2oe
            __panelId__: "4"
          labels: {}
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: o4hlle9mw2ewwf
          title: High Storage Usage
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: prometheus
              model:
                disableTextWrap: false
                editorMode: builder
                expr: proof_server_process_disk_space_usage_MB > 1000
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 30000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            description: The proof server is using more than 1 GB of storage
            summary: High proof server storage usage
            __dashboardUid__: aeies2bb7iy2oe
            __panelId__: "5"
          labels: {}
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
        - uid: proofb6g9px7fs
          title: Proof Server Low ETH Balance
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: prometheus
              model:
                datasource:
                    type: prometheus
                    uid: prometheus
                disableTextWrap: false
                editorMode: builder
                exemplar: false
                expr: eth_balance_ETH{service_name="drosera_proof_server"}
                format: table
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                interval: ""
                intervalMs: 30000
                legendFormat: 'Proof Server: {{proof_server_address}}'
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: C
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.05
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 30000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: aeies2bb7iy2oe
          panelId: 7
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: aeies2bb7iy2oe
            __panelId__: "7"
            description: "The proof server {{ $labels.proof_server_address }} has fallen below the minimum threshold for a safe ETH balance. Current balance: {{ $values.A.Value }} ETH"
            summary: "Low ETH Balance ({{ $values.A.Value }} ETH)"
          labels: {}
          isPaused: false
          notification_settings:
            receiver: Drosera Slack
