{
 "title": "Drosera Operator P2P",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Gossipsub Messages",
   "type": "timeseries",
   "description": "events per second",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(operator_address, ) (rate(gossipsub_messages_total{service_name=\"drosera_operator\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rendezvous Client Discovered",
   "type": "timeseries",
   "description": "events per second",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by(operator_address, ) (rate(rendezvous_client_discovered_total{service_name=\"drosera_operator\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rendezvous Client Registered",
   "type": "timeseries",
   "description": "Events per second",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(operator_address, ) (rate(rendezvous_client_registered_total{service_name=\"drosera_operator\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Identify Received",
   "type": "timeseries",
   "description": "Events per second",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(operator_address, ) (rate(identify_received_total{service_name=\"drosera_operator\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Identify Sent",
   "type": "timeseries",
   "description": "events per second",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by(operator_address, ) (rate(identify_sent_total{service_name=\"drosera_operator\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Established",
   "type": "timeseries",
   "description": "Events per second",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum by(operator_address, ) (rate(swarm_connection_established_total{service_name=\"drosera_operator\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Connection Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(operator_address, ) (rate(swarm_outgoing_connection_error_total{service_name=\"drosera_operator\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Closed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum by(operator_address, ) (rate(swarm_connection_closed_total{service_name=\"drosera_operator\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum by(operator_address, ) (rate(swarm_incoming_connection_total{service_name=\"drosera_operator\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Connection Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by(operator_address, ) (rate(swarm_incoming_connection_error_total{service_name=\"drosera_operator\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dialing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "sum by(operator_address, ) (rate(swarm_dialing_total{service_name=\"drosera_operator\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rendezvous Client Registered Failed",
   "type": "timeseries",
   "description": "event per second",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "sum by(operator_address, ) (rate(rendezvous_client_register_failed_total{service_name=\"drosera_operator\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gossipsub Subscribed",
   "type": "timeseries",
   "description": "events per second",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by(operator_address, ) (rate(gossipsub_subscribed_total{service_name=\"drosera_operator\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Identify Error ",
   "type": "timeseries",
   "description": "Events per second",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "sum by(operator_address, ) (rate(identify_errors_total{service_name=\"drosera_operator\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rendezvous Client Discovered Failed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "sum by(operator_address, ) (rate(rendezvous_client_discovered_failed_total{service_name=\"drosera_operator\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}