{
 "title": "Drosera Operator",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Time to Trap Result",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "execute_trap_duration_milliseconds",
     "legendFormat": "Operator_Trap: {{operator_address}}_{{trap_address}}"
    }
   ]
  },
  {
   "title": "Time to Consensus",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "attestation_consensus_duration_milliseconds",
     "legendFormat": "Operator_Trap: {{operator_address}}_{{trap_address}}"
    }
   ]
  },
  {
   "title": "Connected Peer Percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * ( connected_peers_count / expected_peers_count )",
     "legendFormat": "Operator: {{operator_address}}"
    }
   ]
  },
  {
   "title": "ETH Balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "eth_balance_ETH", "legendFormat": "Operator: {{operator_address}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "drosera_process_memory_usage_MB",
     "legendFormat": "Operator: {{operator_address}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "drosera_process_cpu_usage_percent",
     "legendFormat": "Operator: {{operator_address}}"
    }
   ]
  },
  {
   "title": "Total Disc Write Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "drosera_process_disk_space_usage_MB",
     "legendFormat": "Operator: {{operator_address}}"
    }
   ]
  }
 ]
}