{
 "title": "Drosera Hosted Seed Node",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "seed_node_connected_peers_count",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "seed_node_process_memory_usage_MB",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "seed_node_process_cpu_usage_percent",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Total Disc Write Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "seed_node_process_disk_space_usage_MB",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}