{
 "title": "Drosera Relay Server",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "RPC Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method, service_name) (rate(rpc_request_total{service_name=\"drosera_relay_server\"}[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "drosera_process_memory_usage_MB{service_name=\"drosera_relay_server\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "drosera_process_cpu_usage_percent{service_name=\"drosera_relay_server\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}