{
 "title": "Drosera Seed Node",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Trap Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "trap_count{service_name=\"drosera_seed_node\"}",
     "legendFormat": "{{seed_node_name}}"
    }
   ]
  },
  {
   "title": "Operator Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "operator_count{service_name=\"drosera_seed_node\"}",
     "legendFormat": "{{seed_node_name}}"
    }
   ]
  },
  {
   "title": "RPC request rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (method, seed_node_name) (rate(rpc_request_total{service_name=\"drosera_seed_node\"}[$__interval]))",
     "legendFormat": "{{seed_node_name}} / {{method}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "drosera_process_memory_usage_MB{service_name=\"drosera_seed_node\"}",
     "legendFormat": "{{seed_node_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "drosera_process_cpu_usage_percent{service_name=\"drosera_seed_node\"}",
     "legendFormat": "{{seed_node_name}}"
    }
   ]
  },
  {
   "title": "Total Disc Write Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "drosera_process_disk_space_usage_MB{service_name=\"drosera_seed_node\"}",
     "legendFormat": "{{seed_node_name}}"
    }
   ]
  }
 ]
}