{
 "title": "Drosera Seed Node P2P",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Peer Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "peer_count{service_name=\"drosera_seed_node\"}",
     "legendFormat": "{{seed_node_name}}"
    }
   ]
  },
  {
   "title": "Connection Established",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by(seed_node_name, ) (rate(swarm_connection_established_total{service_name=\"drosera_seed_node\"}[$__rate_interval]))",
     "legendFormat": "{{seed_node_name}}"
    }
   ]
  },
  {
   "title": "Identify Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(seed_node_name, ) (rate(identify_received_total{service_name=\"drosera_seed_node\"}[$__rate_interval]))",
     "legendFormat": "{{seed_node_name}}"
    }
   ]
  },
  {
   "title": "Connection Closed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(seed_node_name, ) (rate(swarm_connection_closed_total{service_name=\"drosera_seed_node\"}[$__rate_interval]))\n",
     "legendFormat": "{{seed_node_name}}"
    }
   ]
  },
  {
   "title": "Identify Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by(seed_node_name, ) (rate(identify_sent_total{service_name=\"drosera_seed_node\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Rendezvous Server Discovered Served",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum by (seed_node_name, ) (rate(rendezvous_server_discovered_served_total{service_name=\"drosera_seed_node\"}[$__rate_interval]))\n",
     "legendFormat": "{{seed_node_name}}"
    }
   ]
  },
  {
   "title": "Rendezvous Server Peer Registered",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (seed_node_name, ) (rate(rendezvous_server_peer_registered_total{service_name=\"drosera_seed_node\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Connection Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum by(seed_node_name, ) (rate(swarm_incoming_connection_error_total{service_name=\"drosera_seed_node\"}[$__rate_interval]))",
     "legendFormat": "{{seed_node_name}}"
    }
   ]
  },
  {
   "title": "Rendezvous Server Registration Expired",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum by (seed_node_name, ) (rate(rendezvous_server_registration_expired_total{service_name=\"drosera_seed_node\"}[$__rate_interval]))\n",
     "legendFormat": "{{seed_node_name}}"
    }
   ]
  },
  {
   "title": "Rendezvous Server Peer Unregistered",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (seed_node_name, ) (rate(rendezvous_server_peer_unregistered_total{service_name=\"drosera_seed_node\"}[$__rate_interval]))",
     "legendFormat": "{{seed_node_name}}"
    }
   ]
  },
  {
   "title": "Rendezvous Server Peer Not Registered",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "sum by (seed_node_name, ) (rate(rendezvous_server_peer_not_registered_total{service_name=\"drosera_seed_node\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rendezvous Server Discovered Not Served",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "sum by (seed_node_name, ) (rate(rendezvous_server_discovered_not_served_total{service_name=\"drosera_seed_node\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Connection Errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by(seed_node_name, ) (rate(swarm_outgoing_connection_error_total{service_name=\"drosera_seed_node\"}[$__rate_interval]))\n",
     "legendFormat": "{{seed_node_name}}"
    }
   ]
  }
 ]
}